import type { Quiz } from "@/app/quiz/page";
import jsPDF from "jspdf";

export function generateQuizPDF(quiz: Quiz) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Colors
  const primaryColor = [30, 232, 118] as const; // #1ee876
  const textColor = [30, 30, 30] as const;
  const mutedColor = [100, 100, 100] as const;

  // Header with logo area
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 35, "F");

  // Title
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Pogo", margin, 22);

  // Quiz title
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(quiz.title, pageWidth - margin, 22, { align: "right" });

  y = 50;

  // Quiz info bar
  doc.setFillColor(245, 245, 245);
  doc.rect(margin, y, contentWidth, 15, "F");
  doc.setTextColor(...mutedColor);
  doc.setFontSize(10);
  doc.text(`${quiz.questions.length} Questions`, margin + 5, y + 10);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin - 5, y + 10, { align: "right" });

  y += 30;

  // Name field
  doc.setTextColor(...textColor);
  doc.setFontSize(11);
  doc.text("Name: ", margin, y);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin + 20, y, margin + 100, y);

  doc.text("Date: ", pageWidth - margin - 60, y);
  doc.line(pageWidth - margin - 40, y, pageWidth - margin, y);

  y += 15;

  // Divider
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);

  y += 15;

  // Questions
  quiz.questions.forEach((question, index) => {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = margin;
    }

    // Question number badge
    doc.setFillColor(...primaryColor);
    doc.roundedRect(margin, y - 5, 10, 10, 2, 2, "F");
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${index + 1}`, margin + 5, y + 2, { align: "center" });

    // Question type badge
    const typeLabel = question.type.replace("-", " ").toUpperCase();
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(margin + 15, y - 5, 30, 10, 2, 2, "F");
    doc.setTextColor(...mutedColor);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(typeLabel, margin + 30, y + 2, { align: "center" });

    y += 12;

    // Question text
    doc.setTextColor(...textColor);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const questionLines = doc.splitTextToSize(question.question, contentWidth - 10);
    doc.text(questionLines, margin + 5, y);
    y += questionLines.length * 6 + 5;

    // Options
    if (question.options) {
      question.options.forEach((option, i) => {
        const letter = String.fromCharCode(65 + i);

        // Option circle
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.3);
        doc.circle(margin + 10, y - 1.5, 3, "S");

        // Option letter
        doc.setTextColor(...mutedColor);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(letter, margin + 10, y, { align: "center" });

        // Option text
        doc.setTextColor(...textColor);
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const optionLines = doc.splitTextToSize(option, contentWidth - 25);
        doc.text(optionLines, margin + 20, y);
        y += optionLines.length * 5 + 4;
      });
    } else if (question.type === "short-answer") {
      // Answer lines for short answer
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.2);
      for (let i = 0; i < 3; i++) {
        doc.line(margin + 5, y + i * 10, pageWidth - margin - 5, y + i * 10);
      }
      y += 35;
    }

    y += 10;
  });

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...mutedColor);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
    doc.text(
      "Generated by Pogo",
      pageWidth - margin,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" }
    );
  }

  // Save the PDF
  doc.save(`${quiz.title.replace(/[^a-z0-9]/gi, "_")}.pdf`);
}
